import numpy as np
zeros=np.zeros((3,3))
print(zeros)
rng =np.arange(10)
print(rng)
lspace = np.linspace(1,4,1)
print(lspace)
emp = np.empty((2,3))
print(emp)
emp_like = np.empty_like(zeros)
print(emp_like)
ide = np.identity(4)
print(ide)
eye = np.eye(4)
print(eye)
arr = np.arange(99).reshape(3,33)
print(arr)
arr = arr.ravel()
print(arr.shape)